version: '3'

services:
  minio:
    image: minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data

  kedro:
    build: .
    depends_on:
      - minio
    environment:
      - KEDRO_ENV=production
    volumes:
      - .:/app
    command: kedro run

volumes:
  minio_data: